#!/usr/bin/python

ROOT_PATH = './../'
USER_INFO_DATA = ROOT_PATH + '/db/db.pkl'

SERVER_NAME = 'localhost'
SERVER_IP = '127.0.0.1'
LISTEN_PORT = 12357
SERVER_ADDR = (SERVER_IP, LISTEN_PORT)

CMD_REGISTER = 0
CMD_LOGIN = 1
CMD_CHATALL = 2
CMD_LOGOUT = 3
CMD_EXIT = 4